version: 2.1

defaults: &defaults
    working_directory: ~/pbourdet
    docker:
        - image: circleci/php:7.4-node
        - image: circleci/mysql:8.0.4
          environment:
              - MYSQL_ALLOW_EMPTY_PASSWORD=true
              - MYSQL_HOST=127.0.0.1
              - MYSQL_DATABASE=pierre-bourdet_test
              - MYSQL_USER=pierre
              - MYSQL_PASSWORD=azerty
              - MYSQL_ROOT_PASSWORD=azerty

commands:
    test_command:
        steps:
            - checkout
            - run:
                  name: Test SSH
                  command: |
                    ssh-keyscan -p 5022 $HOSTNAME >> ~/.ssh/known_hosts
                    sudo apt-get update
                    sudo apt-get install sshpass
                    sshpass -p $SERVERPASS ssh-copy-id $USERNAME@$HOSTNAME -p 5022
                    ssh ghugkvrz@node6-fr.n0c.com -p 5022 'pwd && exit'

jobs:
    test_job:
        <<: *defaults
        steps:
            - add_ssh_keys:
                fingerprint:
                    - "c9:23:91:68:e5:89:8f:9c:36:ce:1c:b7:55:9e:91:ea"
            - test_command

workflows:
    version: 2
    test:
        jobs:
            - test_job
