version: 2.1

defaults: &defaults
    working_directory: ~/pbourdet
    docker:
        - image: circleci/php:7.4-node
        - image: circleci/mysql:8.0.4
          environment:
              - MYSQL_ALLOW_EMPTY_PASSWORD=true
              - MYSQL_HOST=127.0.0.1
              - MYSQL_DATABASE=pierre-bourdet_test
              - MYSQL_USER=pierre
              - MYSQL_PASSWORD=azerty
              - MYSQL_ROOT_PASSWORD=azerty

filter_merge: &filter_merge
    filters:
        branches:
            ignore:
                - master

only_master: &only_master
    filters:
        branches:
            only:
                - master

commands:
    install:
        steps:
            - run:
                  name: Install node packages
                  command: |
                    cd frontend-react/
                    yarn --frozen-lockfile
                    cd ..
            - run:
                  name: Install composer packages
                  command: |
                    cd symfony/
                    composer install
                    cd ..
    phpunit:
        steps:
            - run:
                  name: Run PHPUnits tests
                  command: |
                    cd symfony/
                    ./vendor/bin/simple-phpunit
                    cd ..

    lint:
        steps:
            - run:
                  name: PHP CS Fixer
                  command: |
                      cd symfony/
                      ./vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no
                      cd ..
            - run:
                  name: Yaml lint
                  command: |
                      cd symfony/
                       ./vendor/bin/yaml-lint ./config
                      cd ..

    phpstan:
        steps:
            - run:
                  name: Run PHPStan
                  command: |
                      cd symfony/
                      vendor/bin/phpstan analyse -l 8 src
                      cd ..

jobs:
    check_pr:
        <<: *defaults
        steps:
            - checkout
            - install
            - phpunit
            - lint
            - phpstan
    deploy_prod:
        <<: *defaults
        steps:
            - add_ssh_keys:
                fingerprint:
                    - "c9:23:91:68:e5:89:8f:9c:36:ce:1c:b7:55:9e:91:ea"
            - run:
                  name: Production deploy
                  command: |
                    chmod 755 .circleci/deploy.sh
                    ./.circleci/deploy.sh

workflows:
    version: 2
    check:
        jobs:
            - check_pr:
                  <<: *filter_merge
    deploy:
        jobs:
            - deploy_prod:
                  <<: *only_master
